Fix tests failing with AttributeError raised due to introduction of `label_lower` property in django-mock-queries v2.3.0
Tests raise:
```
self._meta.label_lower = "intecomm_lists.dmtreatments"
    ^^^^^^^^^^^^^^^^^^^^^^

AttributeError: property 'label_lower' of 'MockOptions' object has no setter
```

Caused by MockModel lines like:

`self._meta.label_lower = "intecomm_lists.dmtreatments"`

Change to third party package here: https://github
.com/stphivos/django-mock-queries/commit/87362006e10f99a7f2120780b2018126026fe3df